# Checks json request objects with jq to make sure they are valid
name: json_check
on: 
  # run once a day
  schedule:
    - cron: '31 21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Check jq
        run: |
          jq --version
        shell: bash
      - name: Check for broken json
        run: |
          busted_files = ""
          for file in `find site/docs/src -name "*.json"`; do
            echo $file
            cat $i |jq -j '.' > $i.bk;
            if [ "x$?" != "x0" ]; then
              busted_files = "$busted_files $file"
            fi 
          done
          if [ "x$busted_files" != "x" ] ; then 
            echo "Busted json files"
            echo $busted_files
            exit 1
          find
        shell: bash
